title:            eadams's playworkplay
description:      Experimental Playworkplay.
url:              # Site url.
signoff:          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         Home
    url:          /
  - name:         About
    url:          /about
  - name:         Course
    url:          /course
  - name:         Publications
    url:          /publication
  - name:         Projects
    url:          /project
  - name:         GitHub
    url:          http://github.com/eriqadams
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
